### ISSUE TITLE
Share Screen

### ISSUE THREAD

**Issue by emorling** [Alicunde/Videoconference-Dish-CSS-JS#1]
Thanks for sharing this, it works great! Did you do any thinking or development in regards to having a bigger "shared screen" element in relation to the other video cameras?

**Comment by salbatore** [comment]
Sorry, I forgot about this repository. It would really be quite easy to integrate that functionality. Let's see if I have time and add it.

**Comment by salbatore** [comment]
![e](https://user-images.githubusercontent.com/46431183/143485523-82a05d11-9d4c-49e4-b4ab-7c991189b04f.png)

Now the script have a green button for you 👯

**Comment by emorling** [comment]
Awesome! Thank you @salbatore. It works like a charm 🙏🏽

**Comment by ishan501** [comment]
Hi, there is no green button in the latest demo. the similar screen share icon is not working. Can anyone please guide?
Thanks!
