### ISSUE TITLE
Improvement Algorithm

### ISSUE THREAD

**Issue by nandzz** [Alicunde/Videoconference-Dish-CSS-JS#5]
Hello @salbatore , 

I'll let you my contribution to what I think it's a better algorithm. 

When you calculate the area you can use also this method instead of the loop:

    // Get the board Are
    const boardArea = (Height * Width) 

    // Calculate the tile area
    var tileArea = boardArea / Count

    // Get the sqr 
    const squareRoot = Math.sqrt(tileArea)

    // Get the Width 
    const width = squareRoot - (Math.pow(2, Margin))

    // Get the height
    const height = (width * 0.60)

    return {
        height: height, 
        width: width
    }

**Comment by salbatore** [comment]
Let's see if this weekend I have a time and read your solution. My goal is really to make it easy to read. There are algorithms that do something similar, but are very difficult to understand and, most importantly, difficult to edit.

**Comment by salbatore** [comment]
Hi @nandzz 

I've tested your code, but it doesn't seem to do what the repository claims to do. It must cover an area with the maximum number of squares. Could you make a pull request with your formula?

Thanks!

**Comment by nandzz** [comment]
Hello, @salbatore! Thanks for the try. 

I will check better, but here it seems to work. 
As soon as I have time I will pull your code and make the pull request. Thanks

**Comment by knightcode** [comment]
How's this:

```typescript
  const streamCount = ....;

  function areaFits(possibleWidth: number): boolean {
    const availWidth = ...;
    const availHeight = ...;
    let totalHeightNeeded: number;

    const ratio = 0.75;
    const streamsPerRow = Math.floor(availWidth / possibleWidth);
    const rows = Math.ceil(streamCount / streamsPerRow);
    if (rows > 0) {
      totalHeightNeeded = rows * (possibleWidth * ratio);
    } else {
      // default to one row
      totalHeightNeeded = possibleWidth * ratio;
    }
    return totalHeightNeeded < availHeight;
  }

    let max = 0;
    // binary search for maximal width in  [50, 5000]
    for (let lower = 50, upper = 5000; lower < upper;) {
      max = Math.floor((upper + lower) / 2);
      if (max === lower) {
        break;
      }
      if (areaFits(max)) {
        lower = max;
      } else {
        upper = max;
      }
    }

  console.log("maximum width for each stream:", max);
```
