### ISSUE TITLE
Aspect ratio options

### ISSUE THREAD

**Issue by przemyslawpluta** [Alicunde/Videoconference-Dish-CSS-JS#6]
Would be nice to add options so switch between 1:1, 4:3 and 16:9 aspect ratios.

**Comment by salbatore** [comment]
Hi @przemyslawpluta 

Now you can add new aspect ratios or change in the interface:

![front](https://user-images.githubusercontent.com/46431183/144760766-33476ee1-e2ea-4d61-bbd0-df984c59bd01.gif)

**Comment by przemyslawpluta** [comment]
@salbatore great addition.
