### ISSUE TITLE
Videos not showing across newly added blocks

### ISSUE THREAD

**Issue by przemyslawpluta** [Alicunde/Videoconference-Dish-CSS-JS#7]
If videos are already present in the dash and user adds new empty blocks then toggles video visibility with `la-tv` option result renders videos back only to original blocks not to newly added in.

How to reproduce:
1.  Go to https://alicunde.github.io/Videoconference-Dish-CSS-JS/
2. Add new blocks with `la-plus` while videos are playing and are visible
3. Remove videos with `la-tv` to show only blocks
4. Add videos back with `la-tv` to show videos across blocks
5. Videos are only present across original blocks not across newly added ones

**Comment by salbatore** [comment]
Corrected! thanks @przemyslawpluta
